CREATE DATABASE PROJETO_JOSE;

USE PROJETO_JOSE;

/*CRIANDO AS TABELAS SEGUINDO MODELO LOGICO*/

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM ('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

/*TABELA ASSOCIATIVA*/

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO,ID_COR)
);

/*CONSTRAINTS (REGRAS DE CHAVE)*/

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

/* PREENCHER O BANCO COM NO MINIMO 10 CLIETES */

INSERT INTO CLIENTE VALUES(NULL,'MARIA','F',1);

INSERT INTO CARRO VALUES(NULL,'Gol','ABC-1234',NULL);

INSERT INTO TELEFONE VALUES(NULL,'Cel','(11) 98765-4321',1);

INSERT INTO MARCA VALUES(NULL,'Gol');

INSERT INTO COR VALUES (NULL,'PRETO');


INSERT INTO MARCA VALUES(NULL,'Uno');
INSERT INTO CARRO VALUES(NULL,'Uno','DEF-5678',2);
INSERT INTO CLIENTE VALUES(NULL,'João Santos', 'M', 2);
INSERT INTO TELEFONE VALUES(NULL,'Res', '(11) 2345-6789', 2);
INSERT INTO COR VALUES (NULL,'Prata');































